-- MySQL Script generated by MySQL Workbench
-- Thu Jun 22 11:47:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema disagro1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema disagro1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `disagro1` DEFAULT CHARACTER SET utf8mb3 ;
USE `disagro1` ;

-- -----------------------------------------------------
-- Table `disagro1`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disagro1`.`cliente` ;

CREATE TABLE IF NOT EXISTS `disagro1`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `apellidos` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `disagro1`.`participacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disagro1`.`participacion` ;

CREATE TABLE IF NOT EXISTS `disagro1`.`participacion` (
  `idParticipacion` INT NOT NULL AUTO_INCREMENT,
  `Cliente` INT NOT NULL,
  `descuentoServicios` DECIMAL(3,2) NOT NULL DEFAULT '0.00',
  `descuentoProductos` DECIMAL(3,2) NOT NULL DEFAULT '0.00',
  `fechaHoraParticipacion` DATETIME NOT NULL,
  PRIMARY KEY (`idParticipacion`),
  INDEX `fk_ListadoInteresCliente_Cliente_idx` (`Cliente` ASC) VISIBLE,
  CONSTRAINT `fk_ListadoInteresCliente_Cliente`
    FOREIGN KEY (`Cliente`)
    REFERENCES `disagro1`.`cliente` (`idCliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `disagro1`.`tipo_producto_servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disagro1`.`tipo_producto_servicio` ;

CREATE TABLE IF NOT EXISTS `disagro1`.`tipo_producto_servicio` (
  `idTipoProductoServicio` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoProductoServicio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `disagro1`.`producto_servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disagro1`.`producto_servicio` ;

CREATE TABLE IF NOT EXISTS `disagro1`.`producto_servicio` (
  `idProductoServicio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `precio` DECIMAL(7,2) NOT NULL,
  `tipo` INT NOT NULL,
  PRIMARY KEY (`idProductoServicio`),
  INDEX `fk_ProductoServicio_TipoProductoServicio_idx` (`tipo` ASC) VISIBLE,
  CONSTRAINT `fk_ProductoServicio_TipoProductoServicio`
    FOREIGN KEY (`tipo`)
    REFERENCES `disagro1`.`tipo_producto_servicio` (`idTipoProductoServicio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `disagro1`.`interes_participacion_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disagro1`.`interes_participacion_cliente` ;

CREATE TABLE IF NOT EXISTS `disagro1`.`interes_participacion_cliente` (
  `ProductoServicio` INT NOT NULL,
  `Participacion` INT NOT NULL,
  INDEX `fk_DetalleListadoCliente_ProductoServicio1_idx` (`ProductoServicio` ASC) VISIBLE,
  INDEX `fk_DetalleListadoCliente_ListadoInteresCliente1` (`Participacion` ASC) VISIBLE,
  CONSTRAINT `fk_DetalleListadoCliente_ListadoInteresCliente1`
    FOREIGN KEY (`Participacion`)
    REFERENCES `disagro1`.`participacion` (`idParticipacion`),
  CONSTRAINT `fk_DetalleListadoCliente_ProductoServicio1`
    FOREIGN KEY (`ProductoServicio`)
    REFERENCES `disagro1`.`producto_servicio` (`idProductoServicio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
